using UnityEngine;
using System.Collections;

public class BonusMoveLeft : MonoBehaviour {

	public int hpAmount, muniesAmount;

	Vector3 startPos;
	public float yMovement,xMovement,Freq,time;
	bool move = true;

	void Start(){
		startPos = transform.position;
		//randomness Generated by KillBlock. 
		//B/C Pos is calculated there, as well.	
	}


	void Update () {
		if (move) {
			time += Mathf.PI / 360;
			transform.position = startPos - new Vector3 (-xMovement * time, yMovement * Mathf.Sin (Freq * time), 0);
			transform.localRotation = Quaternion.identity;
		} else {
			transform.localRotation = Quaternion.Lerp 
				(transform.rotation, Quaternion.LookRotation (Vector3.down),Time.deltaTime);
		}
	}

	void OnTriggerEnter2D (Collider2D obj){
		Debug.Log ("bop");
		if (obj.gameObject.tag == "bird" && move) {
			Game_.health+=hpAmount;
			Game_.munies+=muniesAmount;
			SpriteRenderer pic = transform.GetComponent (typeof(SpriteRenderer)) as SpriteRenderer;
			pic.enabled = false;
			move = false;
			Rigidbody2D rb2 = transform.GetComponent (typeof(Rigidbody2D)) as Rigidbody2D;
			//BoxCollider2D bc2 = transform.GetComponent (typeof(BoxCollider2D)) as BoxCollider2D;
			rb2.gravityScale = -1f;
				//bc2.isTrigger = true;
				//rb2.isKinematic = true;
			}
		}
	}

